<a href="https://colab.research.google.com/github/aarohishaiva/phonepay/blob/main/PhonepeSQLsteamlit3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [185]:
!git clone https://github.com/PhonePe/pulse.git
!pip install gitpython

fatal: destination path 'pulse' already exists and is not an empty directory.
Requirement already satisfied: gitpython in /usr/local/lib/python3.10/dist-packages (3.1.43)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.1)

In [186]:
import os
import psycopg2
import json
import git
import pandas as pd

In [187]:
path1="/content/pulse/data/aggregated/transaction/country/india/state/"
Agg_tran_list=os.listdir(path1)

if 'columns1' not in globals():
    columns1={"states":[],"years":[],"quarter":[],"Transaction_type":[],"Transaction_count":[],"Transaction_amount":[]}
if 'agg_tran_list' not in globals():
    # Initialize the variable here
    agg_tran_list = []

for state in agg_tran_list:
    cur_states = path1 + state + "/"  # Define cur_states inside the loop
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_year = cur_states + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, "r")

            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amount)
                columns1["states"].append(state)
                columns1["years"].append(year)
                columns1["quarter"].append(int(file.strip(".json")))

    aggre_transaction = pd.DataFrame(columns1)

    aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
    aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
    aggre_transaction["States"] = aggre_transaction["States"].str.title()
    aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [188]:
path2 = "/content/pulse/data/aggregated/user/country/india/state/"

agg_user_list = os.listdir(path2)

columns2 = {"States":[], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states = path2+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            C = json.load(data)

            try:

                for i in C["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_count"].append(count)
                    columns2["Percentage"].append(percentage)
                    columns2["States"].append(state)
                    columns2["Years"].append(year)
                    columns2["Quarter"].append(int(file.strip(".json")))

            except:
                pass

aggre_user = pd.DataFrame(columns2)

aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [189]:
aggre_user = pd.DataFrame(columns2)

In [190]:
path3 = "/content/pulse/data/aggregated/transaction/country/india/state/"
map_tran_list = os.listdir(path3)

columns3 = {"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}

for state in map_tran_list:
    cur_states = path3+state+"/"
    map_year_list = os.listdir(cur_states)

    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)

        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            E = json.load(data)

            if "hoverDataList" in E["data"]:
               for i in E["data"]["hoverDataList"]:
                   name = i["name"]
                   count = i["metric"][0]["count"]
                   amount = i["metric"][0]["amount"]
                   columns3["District"].append(name)
                   columns3["Transaction_count"].append(count)
                   columns3["Transaction_amount"].append(amount)
                   columns3["States"].append(state)
                   columns3["Years"].append(year)
                   columns3["Quarter"].append(int(file.strip(".json")))
else:
    # Handle the case where the "hoverDataList" key is not present
    pass

map_transaction = pd.DataFrame(columns3)
# Check the data type of the "States" column
data_type = map_transaction["States"].dtype

# Convert the "States" column to string if it's not already
if data_type != str:
    map_transaction["States"] = map_transaction["States"].astype(str)

# Replace the desired values in the "States" column
map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-", " ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [191]:
path4 = "/content/pulse/data/aggregated/transaction/country/india/state/"
map_user_list = os.listdir(path4)

columns4 = {"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states = path4+state+"/"
    map_year_list = os.listdir(cur_states)

    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)

        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            F = json.load(data)

            if "hoverData" in F["data"]:
              for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns4["Districts"].append(district)
                columns4["RegisteredUser"].append(registereduser)
                columns4["AppOpens"].append(appopens)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))
else:
    # Handle the case where the "hoverData" key is not present
    pass

map_user = pd.DataFrame(columns4)
data_type = map_user["States"].dtype

# Print the data type
print(f"Data type of 'States' column: {data_type}")
if data_type != str:
    map_user["States"] = map_user["States"].astype(str)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar")
map_user["States"] = map_user["States"].str.replace("-", " ")
map_user["States"] = map_user["States"].str.title()
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

Data type of 'States' column: float64

In [192]:
path5 = "/content/pulse/data/aggregated/transaction/country/india/state/"
top_tran_list = os.listdir(path5)

columns5 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = path5+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            try:
                for i in H["data"]["pincodes"]:
                    entityName = i["entityName"]
                    count = i["metric"]["count"]
                    amount = i["metric"]["amount"]
                    columns5["Pincodes"].append(entityName)
                    columns5["Transaction_count"].append(count)
                    columns5["Transaction_amount"].append(amount)
                    columns5["States"].append(state)
                    columns5["Years"].append(year)
                    columns5["Quarter"].append(int(file.strip(".json")))

            except:
                pass

top_transaction = pd.DataFrame(columns=["States", "Amount"])

top_transaction["States"] = pd.Series(columns5["States"]).str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar")

top_transaction["Amount"] = columns5["Transaction_amount"]


columns5["Years"].append(year)
top_transaction["States"] = top_transaction["States"].str.replace("-"," ")
top_transaction["States"] = top_transaction["States"].str.title()
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [193]:
path6 = "/content/pulse/data/aggregated/transaction/country/india/state/"
top_user_list = os.listdir(path6)

columns6 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in top_user_list:
    cur_states = path6+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            I = json.load(data)
            if 'pincodes' in I["data"]:
              for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns6["Pincodes"].append(name)
                columns6["RegisteredUser"].append(registereduser)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

top_user = pd.DataFrame(columns6)
data_type = top_user["States"].dtype
print(f"Data type of 'States' column: {data_type}")
top_user["States"] = top_user["States"].astype(str)
missing_values = top_user["States"].isnull().sum()
special_characters = top_user["States"].str.contains(r"[^\w\s]+").sum()

print(f"Number of missing values: {missing_values}")
print(f"Number of rows with special characters: {special_characters}")

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["States"] = top_user["States"].str.replace("-"," ")
top_user["States"] = top_user["States"].str.title()
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

Data type of 'States' column: float64
Number of missing values: 0
Number of rows with special characters: 0

In [194]:
path7= "/content/pulse/data/aggregated/transaction/country/india/state/"

agg_insur_list= os.listdir(path7)

columns7= {"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in agg_insur_list:
    cur_states =path7+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns7["Insurance_type"].append(name)
                columns7["Insurance_count"].append(count)
                columns7["Insurance_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))


aggre_insurance = pd.DataFrame(columns7)

aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"] = aggre_insurance["States"].str.title()
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [195]:
path8= "/content/pulse/data/aggregated/transaction/country/india/state/"

map_insur_list= os.listdir(path8)

columns8= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =path8+state+"/"
    agg_year_list = os.listdir(cur_states)

    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            # Use json.load() to load the JSON data
            with open(cur_files,"r") as f:
                data = json.load(f)
            if "hoverDataList" in D["data"]:
              for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns8["Districts"].append(name)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))


map_insurance = pd.DataFrame(columns8)
data_type = map_insurance["States"].dtype
if data_type != str:
    map_insurance["States"] = map_insurance["States"].astype(str)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [196]:
#Table Creation
#pgsql connection
import sqlite3
from googleapiclient.discovery import build

# Use the correct database driver for SQLite
mydb = sqlite3.connect("/tmp/mysqlite.db")
conn = sqlite3.connect(db_file_path)
cursor = mydb.cursor()

In [197]:
#aggregated transaction table
create_query1 = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

# Check if the variable 'aggre_transaction' is defined
if 'aggre_transaction' in globals():
    # Variable is defined, proceed with the loop
    for index, row in aggre_transaction.iterrows():
        insert_query1 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
        values = (row["States"],
                  row["Years"],
                  row["Quarter"],
                  row["Transaction_type"],
                  row["Transaction_count"],
                  row["Transaction_amount"]
                  )
try:
    cursor.execute(insert_query1, values)
    mydb.commit()
except Exception as e:

    pass

In [198]:
#aggregated user table
create_query2 = '''CREATE TABLE if not exists aggregated_user (
                                                                "States" varchar(50),
                                                                "Years" int,
                                                                "Quarter" int,
                                                                "Brands" varchar(50),
                                                                "Transaction_count" bigint,
                                                                "Percentage" float
                                                                )'''
cursor.execute(create_query2)
mydb.commit()

for index,row in aggre_user.iterrows():
    insert_query2 = '''INSERT INTO aggregated_user ("States", "Years", "Quarter", "Brands", "Transaction_count", "Percentage")
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    try:
        cursor.execute(insert_query2,values)
        mydb.commit()
    except Exception as e:

        pass

In [199]:
#map_transaction_table
create_query3 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query3)
mydb.commit()

for index,row in map_transaction.iterrows():
            insert_query3 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query3,values)
            mydb.commit()

In [200]:
#map_user_table
create_query4 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
cursor.execute(create_query4)
mydb.commit()

for index,row in map_user.iterrows():
    insert_query4 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Districts"],
              row["RegisteredUser"],
              row["AppOpens"])
    cursor.execute(insert_query4,values)
    mydb.commit()

In [201]:
#top_transaction_table
create_query5 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query5)
mydb.commit()

for index,row in top_transaction.iterrows():
    insert_query5 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query5,values)
    mydb.commit()

In [202]:
create_query6 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(create_query6)
mydb.commit()

for index,row in top_user.iterrows():
    insert_query6 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["RegisteredUser"])
    cursor.execute(insert_query6,values)
    mydb.commit()

In [203]:
# Corrected insert query with proper placeholder syntax
insert_query7 = '''
    INSERT INTO aggregated_insurance (States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
    VALUES (?, ?, ?, ?, ?, ?)
'''

# Iterate through the DataFrame and insert data into the table
for index, row in aggre_insurance.iterrows():
    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Insurance_type"],
        row["Insurance_count"],
        row["Insurance_amount"]
    )

    # Execute the corrected insert query with the values tuple
    cursor.execute(insert_query7, values)
    mydb.commit()

In [204]:
#map_insurance_table
create_query8 = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query8)
mydb.commit()

for index,row in map_insurance.iterrows():
            insert_query8 = '''
                INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['Districts'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query8,values)
            mydb.commit()

In [205]:
import streamlit as st
from PIL import Image
import requests
import os

# Set page configuration
st.set_page_config(layout="wide")
st.title("PHONEPE DATA VISUALIZATION AND EXPLORATION")

# Sidebar menu
with st.sidebar:
    select = st.selectbox("Main Menu", ["HOME", "DATA EXPLORATION", "TOP CHARTS"])

# HOME Page
if select == "HOME":
    col1, col2 = st.columns(2)

    with col1:
        st.header("PHONEPE")
        st.subheader("INDIA'S BEST TRANSACTION APP")
        st.markdown("PhonePe is an Indian digital payments and financial technology company.")
        st.write("****FEATURES****")
        st.write("****Credit & Debit card linking****")
        st.write("****Bank Balance check****")
        st.write("****Money Storage****")
        st.write("****PIN Authorization****")
        st.download_button("DOWNLOAD THE APP NOW", "https://www.phonepe.com/app-download/")

    with col2:
        image_url = "https://example.com/image.jpg"  # Replace with the correct image URL
        image_path = "image.jpg"
        # Download the image file
        if not os.path.exists(image_path):
            response = requests.get(image_url)
            with open(image_path, "wb") as f:
                f.write(response.content)
            try:
                  image = Image.open(image_path)
            except IOError:
              raise ValueError(f"Invalid image file format: {image_path}")


    col3, col4 = st.columns(2)

    with col3:

        st.write("****Easy Transactions****")
        st.write("****One App For All Your Payments****")
        st.write("****Your Bank Account Is All You Need****")
        st.write("****Multiple Payment Modes****")
        st.write("****PhonePe Merchants****")

    with col4:
        st.write("****Multiple Ways To Pay****")
        st.write("****1. Direct Transfer & More****")
        st.write("****2. QR Code****")
        st.write("****Earn Great Rewards****")
        st.write("****No Wallet Top-Up Required****")
        st.write("****Pay Directly From Any Bank To Any Bank A/C****")
        st.write("****Instantly & Free****")

# DATA EXPLORATION Page
if select == "DATA EXPLORATION":
    tab1, tab2, tab3 = st.tabs(["Aggregated Analysis", "Map Analysis", "Top Analysis"])

    with tab1:
        method = st.radio("Select The Method", ["Insurance Analysis", "Transaction Analysis", "User Analysis"])

        if method == "Insurance Analysis":
            st.write("Insurance Analysis content goes here.")
            # Your code for Insurance Analysis

        elif method == "Transaction Analysis":
            st.write("Transaction Analysis content goes here.")
            # Your code for Transaction Analysis

        elif method == "User Analysis":
            st.write("User Analysis content goes here.")
            # Your code for User Analysis

    with tab2:
        method_2 = st.radio("Select The Method", ["Map Insurance", "Map Transaction", "Map User"])

        if method_2 == "Map Insurance":
            st.write("Map Insurance content goes here.")
            # Your code for Map Insurance

        elif method_2 == "Map Transaction":
            st.write("Map Transaction content goes here.")
            # Your code for Map Transaction

        elif method_2 == "Map User":
            st.write("Map User content goes here.")
            # Your code for Map User

    with tab3:
        method_3 = st.radio("Select The Method", ["Top Insurance", "Top Transaction", "Top User"])

        if method_3 == "Top Insurance":
            st.write("Top Insurance content goes here.")
            # Your code for Top Insurance

        if method_3 == "Top Transaction":
            st.write("Top Transaction content goes here.")
            # Your code for Top Transaction

        if method_3 == "Top User":
            st.write("Top User content goes here.")
            # Your code for Top User

# TOP CHARTS Page
if select == "TOP CHARTS":
    question = st.selectbox("Select the Question", [
        "1. Transaction Amount and Count of Aggregated Insurance",
        "2. Transaction Amount and Count of Map Insurance",
        "3. Transaction Amount and Count of Top Insurance",
        "4. Transaction Amount and Count of Aggregated Transaction",
        "5. Transaction Amount and Count of Map Transaction",
        "6. Transaction Amount and Count of Top Transaction",
        "7. Transaction Count of Aggregated User",
        "8. Registered users of Map User",
        "9. App opens of Map User",
        "10. Registered users of Top User",
    ])

    if question == "1. Transaction Amount and Count of Aggregated Insurance":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("aggregated_insurance")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("aggregated_insurance")

    elif question == "2. Transaction Amount and Count of Map Insurance":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("map_insurance")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("map_insurance")

    elif question == "3. Transaction Amount and Count of Top Insurance":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("top_insurance")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("top_insurance")

    elif question == "4. Transaction Amount and Count of Aggregated Transaction":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("aggregated_transaction")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("aggregated_transaction")

    elif question == "5. Transaction Amount and Count of Map Transaction":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("map_transaction")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("map_transaction")

    elif question == "6. Transaction Amount and Count of Top Transaction":
        st.subheader("TRANSACTION AMOUNT")
        top_chart_transaction_amount("top_transaction")

        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("top_transaction")

    elif question == "7. Transaction Count of Aggregated User":
        st.subheader("TRANSACTION COUNT")
        top_chart_transaction_count("aggregated_user")

    elif question == "8. Registered users of Map User":
        states = st.selectbox("Select the State", map_user["States"].unique())
        st.subheader("REGISTERED USERS")
        top_chart_registered_user("map_user", states)

    elif question == "9. App opens of Map User":
        states = st.selectbox("Select the State", map_user["States"].unique())
        st.subheader("APPOPENS")
        top_chart_appopens("map_user", states)

    elif question == "10. Registered users of Top User":
        st.subheader("REGISTERED USERS")
        top_chart_registered_users("top_user")

# Placeholder functions
def top_chart_transaction_amount(method):
    st.write(f"Displaying top chart transaction amount for {method}")

def top_chart_transaction_count(method):
    st.write(f"Displaying top chart transaction count for {method}")

def top_chart_registered_user(method, state):
    st.write(f"Displaying registered users for {method} in state {state}")

def top_chart_appopens(method, state):
    st.write(f"Displaying app opens for {method} in state {state}")

def top_chart_registered_users(method):
    st.write(f"Displaying registered users for {method}")